name: Build and Test
on:
  push:
    branches: 
      - supabase-migration
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Zainstaluje przeglądarki Playwright + system deps
      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
        with:
          # opcjonalnie: browsers: 'chromium,firefox,webkit'
          # cache jest domyślnie włączony

      - name: Run tests
        env:
          E2E_USERNAME:           ${{ secrets.E2E_USERNAME }}
          E2E_PASSWORD:           ${{ secrets.E2E_PASSWORD }}
          E2E_USERNAME_ID:        ${{ secrets.E2E_USERNAME_ID }}
          OLLAMA_MOCK:            ${{ secrets.OLLAMA_MOCK }}
          SUPABASE_URL:           ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY:           ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_KEY:   ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: pytest -q
